-- MySQL Script generated by MySQL Workbench
-- mar 31 ago 2021 20:24:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Data` ;
USE `Data` ;

-- -----------------------------------------------------
-- Table `Data`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Data`.`usuarios` (
  `Cedula` VARCHAR(20) NOT NULL,
  `Nombres` VARCHAR(20) NULL DEFAULT NULL,
  `Sexo` VARCHAR(45) NULL DEFAULT NULL,
  `Edad` INT NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `Contrasena` VARCHAR(45) NULL DEFAULT NULL,
  `Estrato` INT NULL DEFAULT NULL,
  `Rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
